apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: k8s-practice
spec:
  containers:
  - name: my-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello Minikube!' > /mnt/data/test.txt && sleep 3600"]
    volumeMounts:
    - name: my-storage
      mountPath: /mnt/data
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc