apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: k8s-practice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual