apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: k8s-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 80